trigger:
  branches:
    include:
      - adf_publish

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'AzureRM' # Replace with your actual service connection name
  location: 'East US 2'
  factoryName: 'sonaf2201-df' # Replace with your actual factory name
  artifactPath: 'adf_publish'
  linkedTemplatesPath: 'adf_publish/sonaf2201-df/linkedTemplates'
  templateFile: 'adf_publish/sonaf2201-df/linkedTemplates/ArmTemplate_master.json'
  parametersFile: 'adf_publish/sonaf2201-df/ARMTemplateParametersForFactory.json'

stages:
- stage: DeployToTest
  displayName: 'Deploy to Test Environment'
  jobs:
  - job: DeployTest
    displayName: 'Deploy ADF to Test'
    steps:

    - task: AzurePowerShell@5
      displayName: 'Stop Triggers (Test)'
      inputs:
        azureSubscription: $(azureServiceConnection)
        ScriptType: 'InlineScript'
        Inline: |
          $DataFactoryName = "$sonaf2201-df"
          $ResourceGroupName = "datafactory-rg376"
          $triggers = Get-AzDataFactoryV2Trigger -ResourceGroupName $ResourceGroupName -DataFactoryName $DataFactoryName
          $triggers | ForEach-Object {
            Stop-AzDataFactoryV2Trigger -ResourceGroupName $ResourceGroupName -DataFactoryName $DataFactoryName -Name $_.Name -Force
          }
        azurePowerShellVersion: 'LatestVersion'

    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy ARM Template to Test'
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(azureServiceConnection)
        subscriptionId: '71e7a52f-b8d6-4ea3-be21-1289c4c19e08'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'datafactory-rg376'
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: $(templateFile)
        csmParametersFile: $(parametersFile)
        overrideParameters: '-factoryName "$(factoryName)"'
        deploymentMode: 'Incremental'

    - task: AzurePowerShell@5
      displayName: 'Start Triggers (Test)'
      inputs:
        azureSubscription: $(azureServiceConnection)
        ScriptType: 'InlineScript'
        Inline: |
          $DataFactoryName = "$(factoryName)"
          $ResourceGroupName = "datafactory-rg376"
          $triggers = Get-AzDataFactoryV2Trigger -ResourceGroupName $ResourceGroupName -DataFactoryName $DataFactoryName
          $triggers | ForEach-Object {
            Start-AzDataFactoryV2Trigger -ResourceGroupName $ResourceGroupName -DataFactoryName $DataFactoryName -Name $_.Name
          }
        azurePowerShellVersion: 'LatestVersion'
